from django.db import models

# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=200)
    account_number = models.CharField(max_length=50)

class Investment_History(models.Model):
    name = models.CharField(max_length=200)
    risk = models.FloatField(u'risk')
    roi_1 = models.FloatField(u'r_1')
    roi_2 = models.FloatField(u'r_2')
    roi_3 = models.FloatField(u'r_3')
    roi_4 = models.FloatField(u'r_4')
    roi_5 = models.FloatField(u'r_5')
    roi_6 = models.FloatField(u'r_6')
    roi_7 = models.FloatField(u'r_7')
    roi_8 = models.FloatField(u'r_8')
    roi_9 = models.FloatField(u'r_9')
    roi_10 = models.FloatField(u'r_11')
    roi_11 = models.FloatField(u'r_11')
    roi_12 = models.FloatField(u'r_12')
    roi_13 = models.FloatField(u'r_13')
    roi_14 = models.FloatField(u'r_14')
    roi_15 = models.FloatField(u'r_15')
    roi_16 = models.FloatField(u'r_16')
    roi_17 = models.FloatField(u'r_17')
    roi_18 = models.FloatField(u'r_18')
    roi_19 = models.FloatField(u'r_19')
    roi_20 = models.FloatField(u'r_20')

class RBC_Customer(models.Model):

    userName = models.CharField(max_length=200)
    income = models.PositiveIntegerField(u'income')
    
    investmentData_1 = models.FloatField(u'i_1')
    investmentData_2 = models.FloatField(u'i_2')
    investmentData_3 = models.FloatField(u'i_3')
    investmentData_4 = models.FloatField(u'i_4')
    investmentData_5 = models.FloatField(u'i_5')
    investmentData_6 = models.FloatField(u'i_6')
    investmentData_7 = models.FloatField(u'i_7')
    investmentData_8 = models.FloatField(u'i_8')
    investmentData_9 = models.FloatField(u'i_9')
    investmentData_10 = models.FloatField(u'i_10')
    investmentData_11 = models.FloatField(u'i_11')
    investmentData_12 = models.FloatField(u'i_12')
    investmentData_13 = models.FloatField(u'i_13')
    investmentData_14 = models.FloatField(u'i_14')
    investmentData_15 = models.FloatField(u'i_15')
    investmentData_16 = models.FloatField(u'i_16')
    investmentData_17 = models.FloatField(u'i_17')
    investmentData_18 = models.FloatField(u'i_18')
    investmentData_19 = models.FloatField(u'i_19')

    roi_1 = models.FloatField(u'r_1')
    roi_2 = models.FloatField(u'r_2')
    roi_3 = models.FloatField(u'r_3')
    roi_4 = models.FloatField(u'r_4')
    roi_5 = models.FloatField(u'r_5')
    roi_6 = models.FloatField(u'r_6')
    roi_7 = models.FloatField(u'r_7')
    roi_8 = models.FloatField(u'r_8')
    roi_9 = models.FloatField(u'r_9')
    roi_10 = models.FloatField(u'r_11')
    roi_11 = models.FloatField(u'r_11')
    roi_12 = models.FloatField(u'r_12')
    roi_13 = models.FloatField(u'r_13')
    roi_14 = models.FloatField(u'r_14')
    roi_15 = models.FloatField(u'r_15')
    roi_16 = models.FloatField(u'r_16')
    roi_17 = models.FloatField(u'r_17')
    roi_18 = models.FloatField(u'r_18')
    roi_19 = models.FloatField(u'r_19')
    roi_20 = models.FloatField(u'r_20')
    
    risk = models.FloatField(u'risk')
    
    clusterID=models.PositiveIntegerField(u'clusterID')

